### ISSUE TITLE
Create BCC Data Custodian Selection Web Interface Gateway

### ISSUE THREAD

**Issue by sardap** [sardap/Capstone-2019-Data-Sharing#137]
What 
* https://docs.google.com/document/d/1_lRcJBDzk_GVl-KngzlZAw8i1Oow1mTCISTak4-r0jA/edit#bookmark=id.7wpugjdwnq5p
* Should be created to run in a docker container

**Comment by 101Lizardman** [comment]
Created branch "Issue#137-GoogleAuth" for figuring out the Google OAuth APIs

**Comment by 101Lizardman** [comment]
Scope increase: Create a smaller operating site to put on Nectar while the rest is being developed in order to gain the access token.

**Comment by 101Lizardman** [comment]
Run the above in Rancher

**Comment by sardap** [comment]
@101Lizardman  Hot off the presses of oh god it's almost week 5 we need to wrap this up is I needed to add some fields to the policy gateway to make it work. We also need to get this to call the addpolicy for the policy gateway when the submit button is pressed. 

The new fields are brokerID which i messaged you on slack about. And for making the request to the policy gateway message me a time which you can discord.

**Comment by 101Lizardman** [comment]
I have just pulled the code from Ahmad and attempted to get it working. It makes the calls to CheckPolicy and AddPolicy and it seems to have a REST call capable of accepting those as parameters but I have no idea how to pass in those variables. I need Ahmad's help with this one.

**Comment by sardap** [comment]
Blocked by #183
