### ISSUE TITLE
Connect other nectar nodes to mulitchian network

### ISSUE THREAD

**Issue by sardap** [sardap/Capstone-2019-Data-Sharing#159]

**Comment by sardap** [comment]
Connected the other 2 const nodes and broker 1 in the multichain network

**Comment by sardap** [comment]
@Davis-A Ran the SSH script How to test this.

Consts nodes should all be apart of it but only broker 1 from the broker side.

to check it ssh into a node
`multichain-cli MainChain getpeerinfo` and you should see the nodes

**Comment by Davis-A** [comment]
@sardap review complete.  
Can you please review my commit on multchain started as service README and unit file
https://github.com/sardap/Capstone-2019-Data-Sharing/pull/182
