### ISSUE TITLE
Create Mock Search Page

### ISSUE THREAD

**Issue by sardap** [sardap/Capstone-2019-Data-Sharing#164]
Create a mock of the data purchase screen. 

Requiments for page can be found here https://docs.google.com/document/d/1_lRcJBDzk_GVl-KngzlZAw8i1Oow1mTCISTak4-r0jA/edit#bookmark=id.uqwwyi2ixz92.

Don't forget that this is located on the **Data Broker**.

**Comment by nhivn** [comment]
@sardap Do we want this page to be available on Data Broker? Or do we only need an image like a simple mockup to be presented?

**Comment by sardap** [comment]
I'm not sure I emailed asking for clarification

**Comment by nhivn** [comment]
I've coded it... but we can put it on hold if he only wants a screenshot. Here is what I've got so far:

![image](https://user-images.githubusercontent.com/20921097/63266853-2c15eb00-c2d4-11e9-8192-07a7fd540822.png)

**Comment by sardap** [comment]
I Sent it to alan it looks great

**Comment by sardap** [comment]
Looks so great im closing this
