### ISSUE TITLE
Check the policy update processes in detail

### ISSUE THREAD

**Issue by sardap** [sardap/Capstone-2019-Data-Sharing#165]

**Comment by sardap** [comment]
@nhivn Can you review these sections
* https://docs.google.com/document/d/1_lRcJBDzk_GVl-KngzlZAw8i1Oow1mTCISTak4-r0jA/edit#bookmark=id.chzyuy72ztcm
* https://docs.google.com/document/d/1_lRcJBDzk_GVl-KngzlZAw8i1Oow1mTCISTak4-r0jA/edit#bookmark=id.xl942olrnblt
* https://docs.google.com/document/d/1_lRcJBDzk_GVl-KngzlZAw8i1Oow1mTCISTak4-r0jA/edit#bookmark=id.cpm93cksqqm
* https://docs.google.com/document/d/1_lRcJBDzk_GVl-KngzlZAw8i1Oow1mTCISTak4-r0jA/edit#bookmark=id.z88b1azmf90
* https://docs.google.com/document/d/1_lRcJBDzk_GVl-KngzlZAw8i1Oow1mTCISTak4-r0jA/edit#bookmark=id.apl0paf4ffc3

**Comment by nhivn** [comment]
@sardap I have read all the design bookmarks you linked. What's the next step? Do you want me to close this issue?

**Comment by sardap** [comment]
Do you have any feedback?
