### ISSUE TITLE
Create Policy Drop Off Point

### ISSUE THREAD

**Issue by sardap** [sardap/Capstone-2019-Data-Sharing#172]
What: https://docs.google.com/document/d/1_lRcJBDzk_GVl-KngzlZAw8i1Oow1mTCISTak4-r0jA/edit#bookmark=id.xl942olrnblt

**Comment by nhivn** [comment]
@sardap @Davis-A 
I'm assuming the Policy Drop Off Point will be its own Docker container? And that we can write it in whatever preferable language we want as long as it works?

**Comment by nhivn** [comment]
@sardap 

I realised a little late that although there are only two params: `policy_creation_token` and `policy_blockchain_location` being passed in the `receivepolicy` post request, we need to save an entry linking the `user_id` and the `policy_creation_token`?

Unless we are creating a table to link only `policy_creation_token` and `policy_blockchain_location`. No association to the `user_id`.

The architectural reference document said that we are going to "Add new entry linking user ID to Policy Token".

So I'm a little confused.

**Comment by sardap** [comment]
The Association can be created when the broker requests the policy creation token for the user. I should have left a disclamer but because it's the broker the implmeantion is pretty much anything goes
