### ISSUE TITLE
Spike report about writing chaincode in multichain

### ISSUE THREAD

**Issue by AhmadBAmzah** [sardap/Capstone-2019-Data-Sharing#178]
Create most basic chain code
- How to deploy
- How to apply to data streams
- Basic chain code rules

**Comment by AhmadBAmzah** [comment]
https://github.com/sardap/Capstone-2019-Data-Sharing/wiki/%23178_Creating_and_Deploying_Smart_Filters

**Comment by sardap** [comment]
Okay so based on this smart fliters won't help us we need a way to append to the active field

**Comment by sardap** [comment]
Il do a proper review later

**Comment by sardap** [comment]
Looks good added to sidebar
