### ISSUE TITLE
Plan Video presentation

### ISSUE THREAD

**Issue by 101Lizardman** [sardap/Capstone-2019-Data-Sharing#202]
Plan the video for the presentation in week 10

**Comment by nhivn** [comment]
**TODO**

- [ ] Review video requirements

**Ideas**

Workflow showing components,  focus on the three parties (user, broker, BCC), trust relationships
Mid-to-high level explanations
What we have done, what is left to do
Documentation is a primary focus to assist the next team to carry on the project
Updates to process from semester 1 to semester 2 (Maybe)
